; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 9600

[env:ndoni]
extends = common
build_flags =
  -D DEVICE_NAME='"NDONI-UPTIME"'
  -D TRACK_PIN=27
  -D MIRROR_PIN=2

[env:akabuga]
extends = common
board = esp32-c3-devkitm-1
build_flags =
  -D DEVICE_NAME='"Akabuga_uptime_bot"'
  -D TRACK_PIN=10
  -D MIRROR_PIN=8
